"""Validates packs/kubernetes/pack.yaml against platform-contract §2:
every JMESPath expression compiles, every strategy/edgeType is in the
closed vocabulary, and packbuild.py's generated `types` covers every
builtin kind."""

from __future__ import annotations

import re

import jmespath
import pytest

from rwdiscovery.chain import BUILTIN_TYPES, CLUSTER, NAMESPACE, resolve_type
from rwdiscovery.enumerate import ApiResource
from rwdiscovery.packbuild import (
    build_crd_summary_expression,
    build_pack_payload,
    builtin_type_specs,
    compute_digest,
    crd_type_specs_and_summaries,
    extra_discovered_type_specs,
    load_pack_yaml,
)

# platform-contract §2's closed strategy/edgeType vocabulary.
VALID_STRATEGIES = {"reference", "owner_reference", "label_selector", "field_join", "path_template", "dns_reference"}
VALID_EDGE_TYPES = {
    "owns", "routes_to", "uses_config", "uses_secret", "mounts", "runs_as", "bound_to",
    "provisioned_by", "scaled_by", "protected_by", "governed_by", "authorized_by", "grants",
    "managed_by", "calls", "assumes_identity",
}  # fmt: skip
VALID_VOLATILITY = {"config", "state"}
VALID_POPULATOR_KINDS = {"projection", "rollup", "task", "agent"}


@pytest.fixture(scope="module")
def pack():
    return load_pack_yaml()


def test_pack_has_required_top_level_keys(pack):
    assert {"name", "version", "platform", "facetDefinitions", "dependencyRules"} <= pack.keys()
    assert "types" not in pack  # generated by packbuild.py, never hand-maintained


def test_every_facet_expression_compiles(pack):
    for facet in pack["facetDefinitions"]:
        assert facet["volatility"] in VALID_VOLATILITY, facet["key"]
        assert facet["populator"]["kind"] in VALID_POPULATOR_KINDS, facet["key"]
        expression = facet["populator"].get("expression")
        if expression:
            jmespath.compile(expression)
        for type_name, by_type_expression in (facet["populator"].get("expressionByType") or {}).items():
            jmespath.compile(by_type_expression), (facet["key"], type_name)


def test_every_dependency_rule_strategy_and_edge_type_are_in_the_closed_vocabulary(pack):
    for rule in pack["dependencyRules"]:
        assert rule["strategy"] in VALID_STRATEGIES, rule["id"]
        assert rule["edgeType"] in VALID_EDGE_TYPES, rule["id"]
        assert rule["direction"] in ("forward", "reverse"), rule["id"]


def test_every_dependency_rule_jmespath_param_compiles(pack):
    jmespath_param_names = {"values", "selector", "targetLabels", "fromValue", "toValue", "typeFrom"}
    for rule in pack["dependencyRules"]:
        for name, value in rule.get("params", {}).items():
            if name in jmespath_param_names and isinstance(value, str):
                jmespath.compile(value)


def test_dns_rule_host_keys_match_host_settings_only(pack):
    rule = next(r for r in pack["dependencyRules"] if r["id"] == "k8s.workload-calls-service-by-dns")
    host_keys = re.compile(rule["params"]["hostKeys"])
    for key in ("DATABASE_HOST", "REDIS_HOST", "host", "DB_ADDR", "SMTP_SERVER", "API_ENDPOINT", "PG_HOSTNAME"):
        assert host_keys.search(key), key
    for key in ("DATABASE_NAME", "FASTAPI_SERVICE", "OTEL_SERVICE_NAME", "GHOST_MODE", "HOSTS_FILE"):
        assert not host_keys.search(key), key


def test_dependency_rule_ids_are_unique(pack):
    ids = [rule["id"] for rule in pack["dependencyRules"]]
    assert len(ids) == len(set(ids))


def test_facet_keys_are_unique(pack):
    keys = [facet["key"] for facet in pack["facetDefinitions"]]
    assert len(keys) == len(set(keys))


def test_builtin_type_specs_cover_the_two_roots_and_every_builtin_kind():
    specs = builtin_type_specs()
    names = {s.type for s in specs}
    assert CLUSTER.type in names
    assert NAMESPACE.type in names
    assert {s.type for s in BUILTIN_TYPES.values()} <= names


_STATIC_KEYS = ("name", "version", "platform", "types", "facetDefinitions", "dependencyRules")


def test_build_pack_payload_shape_and_digest_stability():
    payload = build_pack_payload()
    assert payload["name"] == "kubernetes"
    assert {*_STATIC_KEYS, "digest", "additiveTypes", "additiveFacetDefinitions"} <= payload.keys()
    assert any(t["type"] == "deployment" for t in payload["types"])
    # Idempotent by digest (platform-contract §2): the same inputs must produce the same digest,
    # computed over the static part only -- the additive lists never feed it.
    assert compute_digest({k: payload[k] for k in _STATIC_KEYS}) == payload["digest"]
    again = build_pack_payload()
    assert again["digest"] == payload["digest"]


def _rule(pack, rule_id):
    return next(r for r in pack["dependencyRules"] if r["id"] == rule_id)


def test_generic_workload_rules_exclude_cronjob_and_include_job(pack):
    """CronJob has its own twin rule reading the deeper job-template path
    (`spec.jobTemplate.spec.template.spec...`, not `spec.template.spec...`)
    -- the dependency-rule schema has no `expressionByType` (that is a
    facet-populator-only mechanism), so one rule can't serve both shapes."""
    for rule_id in (
        "k8s.workload-uses-configmap",
        "k8s.workload-uses-secret",
        "k8s.workload-mounts-pvc",
        "k8s.workload-runs-as-serviceaccount",
    ):
        types = _rule(pack, rule_id)["from"]["types"]
        assert "cronjob" not in types, rule_id
        assert "job" in types, rule_id


def test_cronjob_uses_configmap_rule_reads_the_job_template_pod_spec(pack):
    rule = _rule(pack, "k8s.cronjob-uses-configmap")
    cronjob = {
        "spec": {
            "jobTemplate": {
                "spec": {
                    "template": {
                        "spec": {
                            "volumes": [{"name": "cfg", "configMap": {"name": "acme-cronjob-config"}}],
                            "containers": [{"name": "main", "envFrom": [{"configMapRef": {"name": "acme-main-env"}}]}],
                            "initContainers": [
                                {"name": "init", "envFrom": [{"configMapRef": {"name": "acme-init-env"}}]}
                            ],
                        }
                    }
                }
            }
        }
    }
    names = jmespath.compile(rule["params"]["values"]).search(cronjob)
    assert set(names) == {"acme-cronjob-config", "acme-main-env", "acme-init-env"}


def test_deployment_uses_configmap_rule_covers_init_containers(pack):
    rule = _rule(pack, "k8s.workload-uses-configmap")
    deployment = {
        "spec": {
            "template": {
                "spec": {
                    "containers": [{"name": "main", "envFrom": [{"configMapRef": {"name": "acme-main-env"}}]}],
                    "initContainers": [{"name": "init", "envFrom": [{"configMapRef": {"name": "acme-init-env"}}]}],
                }
            }
        }
    }
    names = jmespath.compile(rule["params"]["values"]).search(deployment)
    assert set(names) == {"acme-main-env", "acme-init-env"}


def test_cronjob_uses_secret_rule_covers_init_containers_and_image_pull_secrets(pack):
    rule = _rule(pack, "k8s.cronjob-uses-secret")
    cronjob = {
        "spec": {
            "jobTemplate": {
                "spec": {
                    "template": {
                        "spec": {
                            "containers": [{"name": "main", "envFrom": [{"secretRef": {"name": "acme-main-secret"}}]}],
                            "initContainers": [
                                {"name": "init", "envFrom": [{"secretRef": {"name": "acme-init-secret"}}]}
                            ],
                            "imagePullSecrets": [{"name": "acme-registry"}],
                        }
                    }
                }
            }
        }
    }
    names = jmespath.compile(rule["params"]["values"]).search(cronjob)
    assert set(names) == {"acme-main-secret", "acme-init-secret", "acme-registry"}


def test_cronjob_runs_as_serviceaccount_rule_does_not_default_incorrectly(pack):
    """The generic rule's `spec.template.spec.serviceAccountName || 'default'`
    always evaluated to nothing for a CronJob (wrong path), then silently
    defaulted every one to 'default' regardless of its real service
    account -- the CronJob-specific rule must read the real value."""
    rule = _rule(pack, "k8s.cronjob-runs-as-serviceaccount")
    with_sa = {"spec": {"jobTemplate": {"spec": {"template": {"spec": {"serviceAccountName": "acme-batch-sa"}}}}}}
    without_sa = {"spec": {"jobTemplate": {"spec": {"template": {"spec": {}}}}}}
    assert jmespath.compile(rule["params"]["values"]).search(with_sa) == "acme-batch-sa"
    assert jmespath.compile(rule["params"]["values"]).search(without_sa) == "default"


def test_cronjob_mounts_pvc_rule_reads_the_job_template_pod_spec(pack):
    rule = _rule(pack, "k8s.cronjob-mounts-pvc")
    cronjob = {
        "spec": {
            "jobTemplate": {
                "spec": {
                    "template": {
                        "spec": {"volumes": [{"name": "data", "persistentVolumeClaim": {"claimName": "acme-pvc"}}]}
                    }
                }
            }
        }
    }
    assert jmespath.compile(rule["params"]["values"]).search(cronjob) == ["acme-pvc"]


def _api_resource(group: str, version: str, kind: str, plural: str, namespaced: bool) -> ApiResource:
    spec = resolve_type(group, version, kind, plural, namespaced)
    return ApiResource(
        group=group,
        version=version,
        kind=kind,
        plural=plural,
        namespaced=namespaced,
        verbs=("get", "list"),
        type_spec=spec,
        ephemeral=spec.ephemeral,
    )


def test_extra_discovered_type_specs_registers_aggregated_apis_not_covered_by_builtins_or_crds():
    """`apiregistration.k8s.io/APIService` -- and any other aggregated-API
    or otherwise-uncatalogued resource -- is neither a chain.py builtin nor
    backed by a CustomResourceDefinition object, so without this it would
    never get a registered TypeSpec even though discover.py lists and
    pushes it as an item (platform-contract §3 rejects an unknown
    type)."""
    resources = [
        _api_resource("apiregistration.k8s.io", "v1", "APIService", "apiservices", namespaced=False),
        _api_resource("apps", "v1", "Deployment", "deployments", namespaced=True),  # already a builtin
    ]
    specs = extra_discovered_type_specs(resources, crd_specs=[])
    names = {s.type for s in specs}
    assert names == {"apiservice.apiregistration.k8s.io"}
    assert specs[0].plural == "apiservices.apiregistration.k8s.io"
    assert specs[0].parent == "cluster"


def test_extra_discovered_type_specs_excludes_crd_backed_kinds():
    resources = [_api_resource("cert-manager.io", "v1", "Certificate", "certificates", namespaced=True)]
    crd_specs, _ = crd_type_specs_and_summaries(
        [
            {
                "spec": {
                    "group": "cert-manager.io",
                    "names": {"kind": "Certificate", "plural": "certificates"},
                    "scope": "Namespaced",
                    "versions": [{"name": "v1", "storage": True}],
                }
            }
        ]
    )
    assert extra_discovered_type_specs(resources, crd_specs) == []


def test_build_pack_payload_puts_extra_discovered_types_in_the_additive_part():
    """platform-contract §2: `types` is the static part -- the
    same for every cluster -- so a type this cluster's own discovery
    turned up belongs in `additiveTypes`, never `types`."""
    resources = [_api_resource("apiregistration.k8s.io", "v1", "APIService", "apiservices", namespaced=False)]
    payload = build_pack_payload(discovered_resources=resources)
    assert any(t["type"] == "apiservice.apiregistration.k8s.io" for t in payload["additiveTypes"])
    assert not any(t["type"] == "apiservice.apiregistration.k8s.io" for t in payload["types"])


def test_crd_summary_expression_from_printer_columns():
    columns = [
        {"name": "Ready", "type": "string", "jsonPath": '.status.conditions[?(@.type=="Ready")].status'},
        {"name": "Secret", "type": "string", "jsonPath": ".spec.secretName"},
    ]
    expression = build_crd_summary_expression(columns)
    jmespath.compile(expression)  # must not raise
    assert "spec.secretName" in expression


def test_crd_type_specs_and_summaries_generate_group_qualified_type():
    crd = {
        "spec": {
            "group": "cert-manager.io",
            "names": {"kind": "Certificate", "plural": "certificates", "shortNames": ["cert", "certs"]},
            "scope": "Namespaced",
            "versions": [
                {
                    "name": "v1",
                    "storage": True,
                    "additionalPrinterColumns": [
                        {"name": "Ready", "type": "string", "jsonPath": ".status.conditions[0].status"}
                    ],
                }
            ],
        }
    }
    specs, summaries = crd_type_specs_and_summaries([crd])
    assert specs[0].type == "certificate.cert-manager.io"
    assert specs[0].plural == "certificates.cert-manager.io"
    assert specs[0].parent == "namespace"
    assert "certificate.cert-manager.io" in summaries
    jmespath.compile(summaries["certificate.cert-manager.io"])


def test_build_pack_payload_puts_crd_summaries_in_an_additive_k8s_summary_facet():
    """platform-contract §2: the static `facetDefinitions`'
    `k8sSummary` row is identical for every cluster -- a CRD's printer
    columns are this cluster's own discovery, so they land in
    `additiveFacetDefinitions` instead, keyed the same (`k8sSummary`) so
    papi can upsert the new `expressionByType` entries into the one row a
    workspace is allowed per `(key, origin)`."""
    crd = {
        "spec": {
            "group": "cert-manager.io",
            "names": {"kind": "Certificate", "plural": "certificates"},
            "scope": "Namespaced",
            "versions": [
                {
                    "name": "v1",
                    "storage": True,
                    "additionalPrinterColumns": [
                        {"name": "Ready", "type": "string", "jsonPath": ".status.conditions[0].status"}
                    ],
                }
            ],
        }
    }
    payload = build_pack_payload(discovered_crds=[crd])

    static_summary_facets = [f for f in payload["facetDefinitions"] if f["key"] == "k8sSummary"]
    assert len(static_summary_facets) == 1  # only one row per (key, origin) -- platform-contract §2
    # the static part never carries this cluster's own CRD-derived entries
    assert "certificate.cert-manager.io" not in static_summary_facets[0]["populator"]["expressionByType"]
    assert "deployment" in static_summary_facets[0]["populator"]["expressionByType"]

    additive_summary_facets = [f for f in payload["additiveFacetDefinitions"] if f["key"] == "k8sSummary"]
    assert len(additive_summary_facets) == 1
    assert additive_summary_facets[0]["populator"]["expressionByType"] == {
        "certificate.cert-manager.io": crd_type_specs_and_summaries([crd])[1]["certificate.cert-manager.io"]
    }
    # the additive entry carries nothing else this cluster didn't just discover
    assert "deployment" not in additive_summary_facets[0]["populator"]["expressionByType"]


def test_build_pack_payload_has_no_additive_facet_when_no_crds_discovered():
    payload = build_pack_payload()
    assert payload["additiveFacetDefinitions"] == []
